version: '3.7'
services:
  front-relatorios:
    image: jucema/relatorios_frontend
    container_name: relatorios_frontend
    restart: unless-stopped
    build:
      network: host
      context: .
    ports:
      - '8082:8082'
  
  backend-relatorios:
    image: jucema/relatorios_backend
    container_name: relatorios_backend
    restart: unless-stopped
    environment:
      - PUBLIC_IP=$PUBLIC_IP
    build:
      network: host
      context: ../backend_relatorios
    volumes:
      - $REPORTS_PATH:/app/data
    ports:
      - '8001:8001'