version: '3.7'
services:
  front-relatorios:
    image: jucema/relatorios_frontend
    container_name: relatorios_frontend
    restart: unless-stopped
    environment:
      - API_DNS=$API_DNS
    build:
      network: host
      context: .
    ports:
      - '8082:8082'
  
  backend-relatorios:
    image: jucema/relatorios_backend
    container_name: relatorios_backend
    restart: unless-stopped
    environment:
      - SECRET_KEY=$SECRET_KEY
    build:
      network: host
      context: ../backend_relatorios
    volumes:
      - $DOCUMENTS_PATH:/app/data
    ports:
      - '8001:8001'